
package WSDL;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "accountWS", targetNamespace = "http://serverSOAP.banking.javaguides.net/", wsdlLocation = "http://localhost:8080/?wsdl")
public class AccountWS
    extends Service
{

    private static final URL ACCOUNTWS_WSDL_LOCATION;
    private static final WebServiceException ACCOUNTWS_EXCEPTION;
    private static final QName ACCOUNTWS_QNAME = new QName("http://serverSOAP.banking.javaguides.net/", "accountWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ACCOUNTWS_WSDL_LOCATION = url;
        ACCOUNTWS_EXCEPTION = e;
    }

    public AccountWS() {
        super(__getWsdlLocation(), ACCOUNTWS_QNAME);
    }

    public AccountWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACCOUNTWS_QNAME, features);
    }

    public AccountWS(URL wsdlLocation) {
        super(wsdlLocation, ACCOUNTWS_QNAME);
    }

    public AccountWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACCOUNTWS_QNAME, features);
    }

    public AccountWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccountWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AccountSOAP
     */
    @WebEndpoint(name = "AccountSOAPPort")
    public AccountSOAP getAccountSOAPPort() {
        return super.getPort(new QName("http://serverSOAP.banking.javaguides.net/", "AccountSOAPPort"), AccountSOAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AccountSOAP
     */
    @WebEndpoint(name = "AccountSOAPPort")
    public AccountSOAP getAccountSOAPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serverSOAP.banking.javaguides.net/", "AccountSOAPPort"), AccountSOAP.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACCOUNTWS_EXCEPTION!= null) {
            throw ACCOUNTWS_EXCEPTION;
        }
        return ACCOUNTWS_WSDL_LOCATION;
    }

}
